# Generated by Django 5.0.6 on 2024-05-27 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_match_field_remove_match_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
