# Generated by Django 5.0.6 on 2024-05-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_match_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='field',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='players.field'),
        ),
    ]
