# Generated by Django 5.0.6 on 2024-06-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_match_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_image',
            field=models.ImageField(null=True, upload_to='field_image/'),
        ),
    ]
