# Generated by Django 5.0.6 on 2024-06-03 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_field_field_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='field',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.field'),
        ),
    ]
